name: ai_chat_bot_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^16.0.0
  lottie: ^3.0.0
  flutter_svg: ^2.2.0
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: SF Pro
      fonts:
        - asset: assets/fonts/Fonts/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/Fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/Fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/Fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/Fonts/SF-Pro-Display-Heavy.otf
          weight: 900
  assets:
    - assets/images/
    - assets/animations/
    - assets/fonts/Fonts/
    - assets/icons/
    
